#!/usr/bin/env python3
"""seal_check -- SEAL-003 evidence seal generator + independent validator.

SEAL-003 supersedes SEAL-002 solely because logs-tmp-gen.txt (run-root
input-generation log, 203 B, created 11:15 during A01) was omitted from the
SEAL-002 seal.  This seal enumerates EVERY retained run-root source file
(including logs-tmp-gen.txt) and preserves the four-layer authority model:
  A01_RAW_EXECUTION  : 12 run CSVs + stdout/stderr + inputs + closure/manifest
                       + gen_inputs.py + run_all.sh + logs-tmp-gen.txt
                       (immutable execution/input-generation provenance; the
                       tmp log is provenance of input generation, NOT a new
                       simulation/scientific observation)
  A01_HISTORICAL     : A01 analysis.json/analysis.md + ack/receipt/REVIEW/logs
  A02_CORRECTED      : analysis-corrected.json/md + gen/verify + A02 ack/logs
  SEAL002_HISTORICAL : SEAL-002 attempts files (prior accepted seal, historical)
Read-only on every sealed source; writes only this attempts/A01/ directory.
"""
from __future__ import annotations

import hashlib
import pathlib
import sys

REPO = pathlib.Path('/home/howard/JoSIM')
ROOT = REPO / 'test/final/bvm/runs/bvm-s1-canonical-20260817-01'
TASK = REPO / 'research/tasks/JH-20260817-BVM-S1-002'
SEAL2 = REPO / 'research/tasks/JH-20260817-BVM-S1-SEAL-002'
OUT = pathlib.Path(__file__).parent / 'evidence-seal.yaml'

CASES = ['init_positive_read', 'init_positive_control',
         'init_negative_read', 'init_negative_control']
STEPS = ['0.05ps', '0.025ps', '0.0125ps']


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def entries() -> dict[str, str]:
    e: dict[str, str] = {}
    for case in CASES:
        for step in STEPS:
            d = ROOT / 'raw' / case / step
            e[f'raw/{case}/{step}/run-01.csv'] = 'A01_RAW_EXECUTION'
            e[f'raw/{case}/{step}/stdout.txt'] = 'A01_RAW_EXECUTION'
            e[f'raw/{case}/{step}/stderr.txt'] = 'A01_RAW_EXECUTION'
    for f in sorted((ROOT / 'inputs').glob('*.cir')):
        e[f'inputs/{f.name}'] = 'A01_RAW_EXECUTION'
    for f in ('gen_inputs.py', 'run_all.sh', 'manifest.yaml', 'closure-hashes.txt',
              'logs-tmp-gen.txt'):
        e[f] = 'A01_RAW_EXECUTION'
    e['analysis.json'] = 'A01_HISTORICAL'
    e['analysis.md'] = 'A01_HISTORICAL'
    for f in sorted((TASK / 'attempts/A01').rglob('*')):
        if f.is_file():
            e[f'research/tasks/JH-20260817-BVM-S1-002/attempts/A01/{f.relative_to(TASK / "attempts/A01")}'] = \
                'A01_HISTORICAL'
    e['analysis-corrected.json'] = 'A02_CORRECTED'
    e['analysis-corrected.md'] = 'A02_CORRECTED'
    e['gen_analysis_corrected.py'] = 'A02_CORRECTED'
    e['verify_analysis_corrected.py'] = 'A02_CORRECTED'
    for f in sorted((TASK / 'attempts/A02').rglob('*')):
        if f.is_file():
            e[f'research/tasks/JH-20260817-BVM-S1-002/attempts/A02/{f.relative_to(TASK / "attempts/A02")}'] = \
                'A02_CORRECTED'
    for f in sorted((SEAL2 / 'attempts/A01').rglob('*')):
        if f.is_file():
            e[f'research/tasks/JH-20260817-BVM-S1-SEAL-002/attempts/A01/{f.relative_to(SEAL2 / "attempts/A01")}'] = \
                'SEAL002_HISTORICAL'
    return e


def resolve(rel: str) -> pathlib.Path:
    if rel.startswith('raw/') or rel.startswith('inputs/') or rel in (
            'gen_inputs.py', 'run_all.sh', 'manifest.yaml', 'closure-hashes.txt',
            'logs-tmp-gen.txt', 'analysis.json', 'analysis.md',
            'analysis-corrected.json', 'analysis-corrected.md',
            'gen_analysis_corrected.py', 'verify_analysis_corrected.py'):
        return ROOT / rel
    return REPO / rel


def main() -> None:
    ent = entries()
    hashes = {}
    missing = []
    for rel in ent:
        p = resolve(rel)
        if not p.is_file():
            missing.append(rel)
            continue
        hashes[rel] = sha(p)
    if missing:
        print('MISSING:', *missing, sep='\n  ')
        sys.exit(1)

    ch_lines = [l.split('  ', 1) for l in (ROOT / 'closure-hashes.txt')
                .read_text().splitlines()]
    ch = {p.strip(): h for h, p in ch_lines}
    cross_fail = []
    for rel, h in hashes.items():
        if rel in ch and ch[rel] != h:
            cross_fail.append(f'{rel}: seal {h[:12]} != closure {ch[rel][:12]}')
    if cross_fail:
        print('CROSS-CHECK FAIL (closure-hashes.txt):', *cross_fail, sep='\n  ')
        sys.exit(1)

    lines = [
        '# SEAL-003 evidence seal for JH-20260817-BVM-S1-002 (supersedes',
        '# SEAL-002: adds logs-tmp-gen.txt; generated by seal_check.py;',
        '# read-only; no JoSIM run; no S1/SEAL-002 file modified).',
        '# Authority layers:',
        '#   A01_RAW_EXECUTION  - 12-run CSVs/stdout/stderr/inputs/closure/',
        '#                       manifest/gen_inputs/run_all +',
        '#                       logs-tmp-gen.txt (input-generation/execution',
        '#                       provenance, NOT a simulation observation)',
        '#   A01_HISTORICAL     - A01 analysis.json/md + ack/receipt/REVIEW/logs',
        '#   A02_CORRECTED      - corrected analysis + generator/verifier + A02',
        '#   SEAL002_HISTORICAL - SEAL-002 accepted seal files (historical)',
        'entries:',
    ]
    for rel in sorted(ent):
        lines.append(f'  - {{path: {rel}, sha256: "{hashes[rel]}", authority: {ent[rel]}}}')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    import yaml
    back = yaml.safe_load(OUT.read_text())
    n = len(back['entries'])
    fails = []
    for it in back['entries']:
        p = resolve(it['path'])
        if not p.is_file():
            fails.append(f'{it["path"]}: missing after write')
            continue
        if sha(p) != it['sha256']:
            fails.append(f'{it["path"]}: hash mismatch after write')
        if it['authority'] not in ('A01_RAW_EXECUTION', 'A01_HISTORICAL',
                                   'A02_CORRECTED', 'SEAL002_HISTORICAL'):
            fails.append(f'{it["path"]}: bad authority {it["authority"]}')
    if fails:
        print('POST-WRITE VALIDATION FAIL:', *fails, sep='\n  ')
        sys.exit(1)
    tmp = next((i for i in back['entries'] if i['path'] == 'logs-tmp-gen.txt'), None)
    if tmp is None or tmp['authority'] != 'A01_RAW_EXECUTION':
        print('FAIL: logs-tmp-gen.txt missing or mislabeled in seal')
        sys.exit(1)
    counts = {a: sum(1 for i in back['entries'] if i['authority'] == a)
              for a in ('A01_RAW_EXECUTION', 'A01_HISTORICAL',
                        'A02_CORRECTED', 'SEAL002_HISTORICAL')}
    print(f'SEAL OK: {n} entries {counts}; closure cross-check {len(ch)} OK; '
          f'logs-tmp-gen.txt sealed as A01_RAW_EXECUTION; post-write OK')


if __name__ == '__main__':
    main()
