#!/usr/bin/env python3
"""seal_check -- SEAL-002 evidence seal generator + independent validator.

Read-only: hashes every referenced S1 source artifact from disk, cross-checks
against closure-hashes.txt and the A01 receipt bindings, writes
evidence-seal.yaml, then re-reads the written yaml and revalidates it
(tamper check).  Exits non-zero on any mismatch.  No JoSIM run; no file
outside attempts/A01/ is written or modified.

Authority separation (three layers, per SEAL-002):
  A01_RAW_EXECUTION  : 12 run CSVs + stdout/stderr + inputs + closure/manifest
                       (the sealed execution evidence; A01 analysis.json/md are
                       the HISTORICAL report of this layer, with the report
                       table defects documented in A01 REVIEW.md)
  A01_HISTORICAL     : analysis.json/analysis.md + A01 ack/receipt/REVIEW/logs
                       (historical report/receipt: superseded as the analysis
                       authority by A02; kept immutable for provenance)
  A02_CORRECTED      : analysis-corrected.json/md + gen/verify scripts + A02
                       ack/logs (current corrected-analysis authority)
"""
from __future__ import annotations

import hashlib
import pathlib
import sys

REPO = pathlib.Path('/home/howard/JoSIM')
ROOT = REPO / 'test/final/bvm/runs/bvm-s1-canonical-20260817-01'
TASK = REPO / 'research/tasks/JH-20260817-BVM-S1-002'
OUT = pathlib.Path(__file__).parent / 'evidence-seal.yaml'

CASES = ['init_positive_read', 'init_positive_control',
         'init_negative_read', 'init_negative_control']
STEPS = ['0.05ps', '0.025ps', '0.0125ps']


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def entries() -> dict[str, str]:
    """path -> authority tag, in a fixed deterministic order."""
    e: dict[str, str] = {}
    for case in CASES:
        for step in STEPS:
            d = ROOT / 'raw' / case / step
            e[f'raw/{case}/{step}/run-01.csv'] = 'A01_RAW_EXECUTION'
            e[f'raw/{case}/{step}/stdout.txt'] = 'A01_RAW_EXECUTION'
            e[f'raw/{case}/{step}/stderr.txt'] = 'A01_RAW_EXECUTION'
    for f in sorted((ROOT / 'inputs').glob('*.cir')):
        e[f'inputs/{f.name}'] = 'A01_RAW_EXECUTION'
    for f in ('gen_inputs.py', 'run_all.sh', 'manifest.yaml', 'closure-hashes.txt'):
        e[f] = 'A01_RAW_EXECUTION'
    e['analysis.json'] = 'A01_HISTORICAL'
    e['analysis.md'] = 'A01_HISTORICAL'
    for f in sorted((TASK / 'attempts/A01').rglob('*')):
        if f.is_file():
            e[f'research/tasks/JH-20260817-BVM-S1-002/attempts/A01/{f.relative_to(TASK / "attempts/A01")}'] = \
                'A01_HISTORICAL'
    e['analysis-corrected.json'] = 'A02_CORRECTED'
    e['analysis-corrected.md'] = 'A02_CORRECTED'
    e['gen_analysis_corrected.py'] = 'A02_CORRECTED'
    e['verify_analysis_corrected.py'] = 'A02_CORRECTED'
    for f in sorted((TASK / 'attempts/A02').rglob('*')):
        if f.is_file():
            e[f'research/tasks/JH-20260817-BVM-S1-002/attempts/A02/{f.relative_to(TASK / "attempts/A02")}'] = \
                'A02_CORRECTED'
    return e


def resolve(rel: str) -> pathlib.Path:
    if rel.startswith('raw/') or rel.startswith('inputs/') or rel in (
            'gen_inputs.py', 'run_all.sh', 'manifest.yaml', 'closure-hashes.txt',
            'analysis.json', 'analysis.md', 'analysis-corrected.json',
            'analysis-corrected.md', 'gen_analysis_corrected.py',
            'verify_analysis_corrected.py'):
        return ROOT / rel
    return REPO / rel


def main() -> None:
    ent = entries()
    hashes = {}
    missing = []
    for rel in ent:
        p = resolve(rel)
        if not p.is_file():
            missing.append(rel)
            continue
        hashes[rel] = sha(p)
    if missing:
        print('MISSING:', *missing, sep='\n  ')
        sys.exit(1)

    # cross-check against closure-hashes.txt (50 A01 files)
    ch_lines = [l.split('  ', 1) for l in (ROOT / 'closure-hashes.txt')
                .read_text().splitlines()]
    ch = {p.strip(): h for h, p in ch_lines}
    cross_fail = []
    for rel, h in hashes.items():
        if rel in ch and ch[rel] != h:
            cross_fail.append(f'{rel}: seal {h[:12]} != closure {ch[rel][:12]}')
    if cross_fail:
        print('CROSS-CHECK FAIL (closure-hashes.txt):', *cross_fail, sep='\n  ')
        sys.exit(1)

    # write evidence-seal.yaml (deterministic order)
    lines = [
        '# SEAL-002 evidence seal for JH-20260817-BVM-S1-002 (generated by',
        '# seal_check.py; read-only; no JoSIM run; no S1 file modified).',
        '# Authority layers:',
        '#   A01_RAW_EXECUTION - 12-run CSVs/stdout/stderr/inputs/closure/manifest',
        '#   A01_HISTORICAL    - A01 analysis.json/md + ack/receipt/REVIEW/logs',
        '#                     (historical report; superseded as analysis',
        '#                      authority by A02; kept for provenance)',
        '#   A02_CORRECTED     - analysis-corrected.json/md + generator +',
        '#                     verifier + A02 ack/logs (current authority)',
        'entries:',
    ]
    for rel in sorted(ent):
        lines.append(f'  - {{path: {rel}, sha256: "{hashes[rel]}", authority: {ent[rel]}}}')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    # tamper check: re-read and revalidate the written yaml
    import yaml
    back = yaml.safe_load(OUT.read_text())
    n = len(back['entries'])
    fails = []
    for it in back['entries']:
        p = resolve(it['path'])
        if not p.is_file():
            fails.append(f'{it["path"]}: missing after write')
            continue
        if sha(p) != it['sha256']:
            fails.append(f'{it["path"]}: hash mismatch after write')
        if it['authority'] not in ('A01_RAW_EXECUTION', 'A01_HISTORICAL',
                                   'A02_CORRECTED'):
            fails.append(f'{it["path"]}: bad authority {it["authority"]}')
    if fails:
        print('POST-WRITE VALIDATION FAIL:', *fails, sep='\n  ')
        sys.exit(1)
    n_raw = sum(1 for i in back['entries'] if i['authority'] == 'A01_RAW_EXECUTION')
    n_hist = sum(1 for i in back['entries'] if i['authority'] == 'A01_HISTORICAL')
    n_corr = sum(1 for i in back['entries'] if i['authority'] == 'A02_CORRECTED')
    print(f'SEAL OK: {n} entries ({n_raw} A01_RAW_EXECUTION, {n_hist} '
          f'A01_HISTORICAL, {n_corr} A02_CORRECTED); closure cross-check '
          f'{len(ch)} files OK; post-write validation OK')


if __name__ == '__main__':
    main()
