#!/usr/bin/env python3
"""verify_inventory -- S2-SEAL-001 recursive hash inventory + validator.

Read-only: recursively enumerates every regular file under the original S2
run root (bvm-s2-load-20260817-01), records exact repo-relative path,
SHA-256, byte size and provenance layer in evidence-inventory.yaml; then
revalidates the written inventory (hash recompute + path-set equality) and
binds the original S2 request/ACK/receipt as HISTORICAL_PROTOCOL_
NOT_FINAL_AUTHORITY.  Writes ONLY inside this attempts/A01/ directory.
No JoSIM run; no original S2 file is touched.
"""
from __future__ import annotations

import hashlib
import pathlib
import sys

REPO = pathlib.Path('/home/howard/JoSIM')
ROOT = REPO / 'test/final/bvm/runs/bvm-s2-load-20260817-01'
S2 = REPO / 'research/tasks/JH-20260817-BVM-S2-001'
OUT = pathlib.Path(__file__).parent / 'evidence-inventory.yaml'

LAYERS = {
    'inputs/': 'S2_EXECUTION_INPUT',
    'raw/': 'S2_EXECUTION_RAW',
    'logs/': 'S2_EXECUTION_LOG',
    'gen_inputs.py': 'S2_EXECUTION_TOOL',
    'run_all.sh': 'S2_EXECUTION_TOOL',
    'analyze_s2.py': 'S2_ANALYSIS_TOOL',
    'analysis.json': 'S2_ANALYSIS_RESULT',
    'analysis.md': 'S2_ANALYSIS_RESULT',
    'manifest.yaml': 'S2_EXECUTION_MANIFEST',
    'closure-hashes.txt': 'S2_EXECUTION_CLOSURE',
}


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def layer(rel: str) -> str:
    for prefix, l in LAYERS.items():
        if rel.startswith(prefix):
            return l
    return 'S2_RUN_ROOT_FILE'


def main() -> None:
    files = {}
    for p in ROOT.rglob('*'):
        if p.is_file():
            rel = p.relative_to(ROOT).as_posix()
            files[rel] = (sha(p), p.stat().st_size, layer(rel))
    if not files:
        print('FAIL: empty run-root inventory')
        sys.exit(1)

    lines = [
        '# S2-SEAL-001 evidence inventory for bvm-s2-load-20260817-01',
        '# (generated by verify_inventory.py; read-only; no JoSIM; original',
        '#  S2 task/run-root files untouched).',
        '# Provenance layers:',
        '#   S2_EXECUTION_INPUT/RAW/LOG/MANIFEST/CLOSURE/TOOL - execution',
        '#   S2_ANALYSIS_TOOL/RESULT - analysis',
        '#   HISTORICAL_PROTOCOL_NOT_FINAL_AUTHORITY - original S2',
        '#   request/ACK/receipt (original verify-task fails only on the',
        '#   ACK baseline.git_head mismatch: 96599fc request vs b3a467d ACK)',
        'files:',
    ]
    for rel in sorted(files):
        h, sz, l = files[rel]
        lines.append(f'  - {{path: {rel}, sha256: "{h}", bytes: {sz}, layer: {l}}}')
    lines.append('historical_protocol:')
    for rel, tag in [('research/tasks/JH-20260817-BVM-S2-001/request.yaml',
                      'ORIGINAL_REQUEST'),
                     ('research/tasks/JH-20260817-BVM-S2-001/attempts/A01/ack.yaml',
                      'ORIGINAL_ACK'),
                     ('research/tasks/JH-20260817-BVM-S2-001/attempts/A01/receipt.yaml',
                      'ORIGINAL_RECEIPT')]:
        p = REPO / rel
        if p.is_file():
            lines.append(
                '  - {path: ' + rel + ', sha256: "' + sha(p) +
                '", authority: HISTORICAL_PROTOCOL_NOT_FINAL_AUTHORITY, tag: ' +
                tag + '}')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    import yaml
    back = yaml.safe_load(OUT.read_text())
    n = len(back['files'])
    fails = []
    for it in back['files']:
        p = ROOT / it['path']
        if not p.is_file():
            fails.append(f'{it["path"]}: missing after write')
            continue
        if sha(p) != it['sha256']:
            fails.append(f'{it["path"]}: hash mismatch after write')
        if p.stat().st_size != it['bytes']:
            fails.append(f'{it["path"]}: size mismatch')
    live = {p.relative_to(ROOT).as_posix() for p in ROOT.rglob('*') if p.is_file()}
    inv = {it['path'] for it in back['files']}
    if live != inv:
        fails.append(f'path-set mismatch: live {len(live)} vs inventory {len(inv)}')
    if fails:
        print('POST-WRITE VALIDATION FAIL:', *fails, sep='\n  ')
        sys.exit(1)
    hist = back.get('historical_protocol', [])
    if len(hist) != 3:
        print(f'FAIL: expected 3 historical protocol records, got {len(hist)}')
        sys.exit(1)
    print(f'INVENTORY OK: {n} files ({len(live)} live == {len(inv)} inventory); '
          f'historical protocol: {len(hist)} records bound; post-write OK')


if __name__ == '__main__':
    main()
