#!/usr/bin/env python3
"""build_evidence_bundle -- optional recursive evidence bundle builder.

Builds a recursive manifest over required evidence files
(raw/inputs/logs/manifest/spec/analyzer/verifier/structured result/
renderer/report/inventory/receipt) with SHA-256 and byte size per file,
then revalidates the written bundle (every hash recomputed, every required
role present at least once, no missing required file).  A path argument may
be a directory: its whole file tree is expanded recursively (one entry per
file, same role).  Multiple entries per role are allowed.  Writes the bundle
manifest to the given output path.  Missing required files fail (exit 1).

The bundle is a PRE-receipt manifest: it must never hash the final receipt
itself (the receipt binds the bundle, not vice versa).

Usage:
  python3 build_evidence_bundle.py out.yaml <path> <role> [<path> <role> ...]
"""
from __future__ import annotations

import hashlib
import pathlib
import sys

REQUIRED_ROLES = {
    'raw', 'inputs', 'logs', 'manifest', 'spec', 'analyzer', 'verifier',
    'structured_result', 'renderer', 'report', 'inventory', 'receipt',
}


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def expand(p_str: str) -> list[str]:
    """Resolve one path argument to concrete files; directories are expanded
    recursively (exact path-set = every file under the tree)."""
    p = pathlib.Path(p_str)
    if p.is_dir():
        return sorted(rel.as_posix() for rel in p.rglob('*')
                      if rel.is_file())
    return [p_str]


def main() -> None:
    if len(sys.argv) < 3 or (len(sys.argv) - 2) % 2 != 0:
        print('usage: build_evidence_bundle.py out.yaml <path> <role> ...')
        sys.exit(2)
    out = pathlib.Path(sys.argv[1])
    pairs = list(zip(sys.argv[2::2], sys.argv[3::2]))
    missing = []
    entries = []
    provided_roles = set()
    for p_str, role in pairs:
        if role not in REQUIRED_ROLES:
            print(f'FAIL: unknown role {role}')
            sys.exit(1)
        provided_roles.add(role)
        for concrete in expand(p_str):
            p = pathlib.Path(concrete)
            if not p.is_file():
                missing.append(f'{role}: {concrete}')
                continue
            entries.append((concrete, role, sha(p), p.stat().st_size))
    absent = REQUIRED_ROLES - provided_roles
    if absent:
        for r in sorted(absent):
            missing.append(f'{r}: <not provided>')
    if missing:
        print('BUNDLE FAIL — missing required evidence:')
        for m in missing:
            print(f'  - {m}')
        sys.exit(1)

    lines = [
        '# evidence bundle manifest (generated by build_evidence_bundle.py)',
        'entries:',
    ]
    for p_str, role, h, sz in sorted(entries, key=lambda e: (e[1], e[0])):
        lines.append(f'  - {{path: {p_str}, role: {role}, sha256: "{h}", '
                     f'bytes: {sz}}}')
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    import yaml
    back = yaml.safe_load(out.read_text())
    roles = [it['role'] for it in back['entries']]
    if not REQUIRED_ROLES.issubset(set(roles)):
        print('FAIL: written bundle role set incomplete')
        sys.exit(1)
    for it in back['entries']:
        p = pathlib.Path(it['path'])
        if not p.is_file():
            print(f'FAIL: {it["path"]} missing after write')
            sys.exit(1)
        if sha(p) != it['sha256'] or p.stat().st_size != it['bytes']:
            print(f'FAIL: {it["path"]} mismatch after write')
            sys.exit(1)
    print(f'BUNDLE OK: {len(entries)} entries ({len(set(roles))} roles), '
          f'all {len(REQUIRED_ROLES)} required roles present at least once; '
          f'post-write revalidation OK')


if __name__ == '__main__':
    main()
