#!/usr/bin/env python3
"""build_evidence_bundle -- optional recursive evidence bundle builder.

Builds a recursive manifest over required evidence files
(raw/inputs/logs/manifest/spec/analyzer/verifier/structured result/
renderer/report/inventory/receipt) with SHA-256 and byte size per file,
then revalidates the written bundle (every hash recomputed, all required
roles present, no extra required-role file missing).  Writes the bundle
manifest to the given output path.  Missing required files fail (exit 1).

Usage:
  python3 build_evidence_bundle.py out.yaml <path> <role> [<path> <role> ...]
"""
from __future__ import annotations

import hashlib
import pathlib
import sys

REQUIRED_ROLES = {
    'raw', 'inputs', 'logs', 'manifest', 'spec', 'analyzer', 'verifier',
    'structured_result', 'renderer', 'report', 'inventory', 'receipt',
}


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main() -> None:
    if len(sys.argv) < 3 or (len(sys.argv) - 2) % 2 != 0:
        print('usage: build_evidence_bundle.py out.yaml <path> <role> ...')
        sys.exit(2)
    out = pathlib.Path(sys.argv[1])
    pairs = list(zip(sys.argv[2::2], sys.argv[3::2]))
    seen_roles = set()
    missing = []
    entries = []
    for p_str, role in pairs:
        if role not in REQUIRED_ROLES:
            print(f'FAIL: unknown role {role}')
            sys.exit(1)
        if role in seen_roles:
            print(f'FAIL: duplicate role {role}')
            sys.exit(1)
        seen_roles.add(role)
        p = pathlib.Path(p_str)
        if not p.is_file():
            missing.append(f'{role}: {p_str}')
            continue
        entries.append((p_str, role, sha(p), p.stat().st_size))
    absent = REQUIRED_ROLES - seen_roles
    if absent:
        for r in sorted(absent):
            missing.append(f'{r}: <not provided>')
    if missing:
        print('BUNDLE FAIL — missing required evidence:')
        for m in missing:
            print(f'  - {m}')
        sys.exit(1)

    lines = [
        '# evidence bundle manifest (generated by build_evidence_bundle.py)',
        'entries:',
    ]
    for p_str, role, h, sz in sorted(entries, key=lambda e: e[1]):
        lines.append(f'  - {{path: {p_str}, role: {role}, sha256: "{h}", '
                     f'bytes: {sz}}}')
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    import yaml
    back = yaml.safe_load(out.read_text())
    roles = [it['role'] for it in back['entries']]
    if set(roles) != REQUIRED_ROLES or len(roles) != len(REQUIRED_ROLES):
        print('FAIL: written bundle role set incomplete')
        sys.exit(1)
    for it in back['entries']:
        p = pathlib.Path(it['path'])
        if sha(p) != it['sha256'] or p.stat().st_size != it['bytes']:
            print(f'FAIL: {it["path"]} mismatch after write')
            sys.exit(1)
    print(f'BUNDLE OK: {len(entries)} entries, all {len(REQUIRED_ROLES)} '
          f'required roles present; post-write revalidation OK')


if __name__ == '__main__':
    main()
